### ISSUE TITLE
Cannot find module './build/Release/shell' with v0.3.1

### ISSUE THREAD

**Issue by nwinkler** [cri5ti/grunt-shell-spawn#29]
After updating to v0.3.1, I'm getting the following error when running the shell task:

```
Cannot find module './build/Release/shell'
```

Here's the respective configuration from my `Grunfile.js`:

```
        shell: {
            xvfb: {
                command: 'Xvfb :99 -ac -screen 0 1600x1200x24',
                options: {
                    async: true
                }
            }
        }
```

Do I need to update my configuration when using v0.3.1? Reverting to v0.3.0 fixes the issue immediately.

**Comment by nwinkler** [comment]
Is this caused by the change in #18?

**Comment by ValentinH** [comment]
:thumbsup: same here

**Comment by utkukaratas** [comment]
seconded. 0.3.0 seems to work.

**Comment by ip2k** [comment]
+1, this has broken our automated testing :<

**Comment by radutopala** [comment]
:+1: same here, 0.3.0 works fine.

**Comment by dandv** [comment]
Is this still a problem, or can we close?

**Comment by cri5ti** [comment]
This issue seems to have been caused by the use of `execSync`, which has been replaced with `sync-exec` since 0.3.2. 
Closing the issue.
